[ci] Add layers to gitlab pipeline
Former-commit-id: 1caa16207f285d401a5b2f49f1dc373eb3a59d24

diff --git a/tools/ci/gitlab-ci.yml b/tools/ci/gitlab-ci.yml
--- a/tools/ci/gitlab-ci.yml
+++ b/tools/ci/gitlab-ci.yml
@@ -1,7 +1,7 @@
 stages:
   - build
   - test
-  - coverage
+  - post build
   - docs
   # - deploy
 
@@ -10,6 +10,8 @@ variables:
 
 build:clang-8:debug:
   stage: build
+  tags:
+    - linux
   script:
     - mkdir build-clang8-debug
     - nice cmake -S . -B build-clang8-debug 
@@ -27,6 +29,8 @@ build:clang-8:debug:
 
 build:clang-8:asan-ubsan:
   stage: build
+  tags:
+    - linux
   script:
     - mkdir build-clang8-asan-ubsan
     - nice cmake -S . -B build-clang8-asan-ubsan 
@@ -45,6 +49,8 @@ build:clang-8:asan-ubsan:
 
 build:clang-8:tsan:
   stage: build
+  tags:
+    - linux
   script:
     - mkdir build-clang8-tsan
     - nice cmake -S . -B build-clang8-tsan 
@@ -63,6 +69,8 @@ build:clang-8:tsan:
 
 build:clang-8:release:
   stage: build
+  tags:
+    - linux
   script:
     - mkdir build-clang8-release
     - nice cmake -S . -B build-clang8-release 
@@ -80,6 +88,8 @@ build:clang-8:release:
 
 build:gcc-7:debug:
   stage: build
+  tags:
+    - linux
   script:
     - mkdir build-gcc7-debug
     - nice cmake -S . -B build-gcc7-debug 
@@ -95,8 +105,30 @@ build:gcc-7:debug:
     paths:
       - build-gcc7-debug/bin
 
+build:gcc-7:coverage:
+  stage: build
+  tags:
+    - linux
+  script:
+    - mkdir build-gcc7-coverage
+    - nice cmake -S . -B build-gcc7-coverage
+      -DCMAKE_BUILD_TYPE=Debug
+      -DCMAKE_C_COMPILER=/usr/local/lib/ccache/gcc-7
+      -DCMAKE_CXX_COMPILER=/usr/local/lib/ccache/g++-7
+      -DBVEREBORN_CODE_COVERAGE=On
+      -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake 
+      -DCMAKE_{EXE,SHARED}_LINKER_FLAGS="-fuse-ld=gold"
+      -DCMAKE_EXPORT_COMPILE_COMMANDS=On
+      -GNinja
+    - nice ninja -C build-gcc7-coverage
+  artifacts:
+    paths:
+      - build-gcc7-coverage/bin
+
 build:gcc-7:release:
   stage: build
+  tags:
+    - linux
   script:
     - mkdir build-gcc7-release
     - nice cmake -S . -B build-gcc7-release 
@@ -114,6 +146,8 @@ build:gcc-7:release:
 
 test:clang-8:debug:
   stage: test
+  tags:
+    - linux
   script:
     - LD_LIBRARY_PATH=$PWD/build-clang8-debug/bin nice ./build-clang8-debug/bin/test-runner
   dependencies:
@@ -121,6 +155,8 @@ test:clang-8:debug:
 
 test:clang-8:asan-ubsan:
   stage: test
+  tags:
+    - linux
   script:
     - LD_LIBRARY_PATH=$PWD/build-clang8-asan-ubsa/bin nice ./build-clang8-asan-ubsan/bin/test-runner
   dependencies:
@@ -128,6 +164,8 @@ test:clang-8:asan-ubsan:
 
 test:clang-8:tsan:
   stage: test
+  tags:
+    - linux
   script:
     - LD_LIBRARY_PATH=$PWD/build-clang8-tsan/bin nice ./build-clang8-tsan/bin/test-runner
   dependencies:
@@ -135,6 +173,8 @@ test:clang-8:tsan:
 
 test:clang-8:release:
   stage: test
+  tags:
+    - linux
   script:
     - LD_LIBRARY_PATH=$PWD/build-clang8-release/bin nice ./build-clang8-release/bin/test-runner
   dependencies:
@@ -142,6 +182,8 @@ test:clang-8:release:
 
 test:gcc-7:debug:
   stage: test
+  tags:
+    - linux
   script:
     - LD_LIBRARY_PATH=$PWD/build-gcc7-debug/bin nice ./build-gcc7-debug/bin/test-runner
   dependencies:
@@ -149,26 +191,53 @@ test:gcc-7:debug:
 
 test:gcc-7:release:
   stage: test
+  tags:
+    - linux
   script:
     - LD_LIBRARY_PATH=$PWD/build-gcc7-release/bin nice ./build-gcc7-release/bin/test-runner
   dependencies:
     - build:gcc-7:release
 
-coverage:gcc-7:debug:
-  stage: coverage
+docs:
+  stage: post build
+  tags:
+    - linux
   script:
-    - curl -so codecov.bash https://codecov.io/bash
-    - mkdir build-gcc7-coverage
-    - nice cmake -S . -B build-gcc7-coverage
+    - nice ./tools/docs/linux.sh build-docs
+  artifacts:
+    paths:
+      - build-docs/html/
+  dependencies:
+
+format:
+  stage: post build
+  tags:
+    - linux
+  only:
+    - /^dev$/
+    - merge_requests
+  script: 
+    - mkdir build-format
+    - nice cmake -S . -B build-format 
       -DCMAKE_BUILD_TYPE=Debug
       -DCMAKE_C_COMPILER=/usr/local/lib/ccache/gcc-7
       -DCMAKE_CXX_COMPILER=/usr/local/lib/ccache/g++-7
-      -DBVEREBORN_CODE_COVERAGE=On
       -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake 
-      -DCMAKE_{EXE,SHARED}_LINKER_FLAGS="-fuse-ld=gold"
-      -DCMAKE_EXPORT_COMPILE_COMMANDS=On
       -GNinja
-    - nice ninja -C build-gcc7-coverage
+    - nice ninja -C build-format format
+    - if [ `git status --porcelain lib src | wc -c` -eq 0 ]; then
+          echo "No formatting errors found.";
+      else
+          echo "Formatting errors found.";
+          git diff lib src;
+          exit 1;
+      fi
+
+coverage:
+  stage: post build
+  tags:
+    - linux
+  script:
     - cd build-gcc7-coverage
     - nice lcov -c -i -d . -o empty-coverage.info --gcov-tool gcov-7
     - LD_LIBRARY_PATH=$PWD/bin bin/test-runner
@@ -177,11 +246,6 @@ coverage:gcc-7:debug:
     - nice lcov --remove coverage.info "/usr/*" "$CI_PROJECT_DIR/extern/*" "*/vcpkg/*" "*/tests/*" "*/tests_old/*" --output-file coverage.info
     - nice lcov --list coverage.info
     - bash ../codecov.bash -f coverage.info -t '2bfac9df-f504-4c34-bc53-3803bb9c9b27' || echo "Codecov did not collect coverage reports"
-
-doxygen:
-  stage: docs
-  script:
-    - nice ./tools/docs/linux.sh build-docs
-  artifacts:
-    paths:
-      - build-docs/html/
+  coverage: '/\s+Total:\|(\d+\.?\d*)%/'
+  dependencies:
+    - build:gcc-7:coverage
